Feature add for stats pulled by conference
j-andrews7/kenpompy pull request #50
Opened 2023-03-18 12:04 UTC by WakeUpWaffles

I have implemented pulling stats by conferences. They're pulled from this [url](https://kenpom.com/conf.php?c=B10). 

It currently pulls:
- Conference ids for a given season
- Aggregate stats for the whole conference
- Standing stats
- Offense stats
- Defense stats

Let me know if there are any changes/additions for the conferences page.
Logan

2023-03-18 18:27 UTC, esqew commented
Thanks for the PR! I should be able to get to reviewing and providing feedback in the next week or so.

2023-03-19 00:06 UTC, esqew requested changes
Once the comments are addressed I'll give this a functional test. Thanks again for the PR!

2023-03-19 14:52 UTC, j-andrews7 approved these changes
Agree with Sean on everything. Looks good.

2023-03-19 14:52 UTC, j-andrews7 commented on tests/test_conference.py
> +
Another nitpick, can you tighten up the spacing in these and have two empty lines between functions? Otherwise looks good to me, thanks for the PR!

2023-03-19 16:52 UTC, WakeUpWaffles commented on kenpompy/conference.py
> +def get_aggregate_stats(browser, conf, season=None):
Good catch on that url. I was trying to find a way to get all of them without calling each conferences. I can get that added.

2023-03-19 16:54 UTC, WakeUpWaffles commented
Thanks for the input! I should be able to get those done by today!

2023-03-20 00:22 UTC, esqew approved these changes

2023-03-20 00:24 UTC, merged

2023-03-20 00:28 UTC, esqew commented
Thanks again for this PR. Fantastic work on this feature!